import type { EditorialContentBrief } from "@/lib/editorial-content-brief";

/** Shared briefs for the audited editorial cluster pages. */
export const editorialContentBriefs = {
  china: {
    primaryKeyword: "vpn for china",
    intent: "commercial",
    cluster: "censorship-restricted-networks",
    lastReviewedAt: "2026-08-11",
    evidence: ["docs/research/dataforseo-china-cluster-2026-08-11.md", "/methodology", "https://freedomhouse.org/country/china/freedom-net/2025"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  freeVpn: {
    primaryKeyword: "best free vpn",
    intent: "commercial",
    cluster: "free-and-low-cost-access",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-free-vpn-cluster-2026-08-13.md", "/methodology", "https://protonvpn.com/free-vpn/download"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  cheapVpn: {
    primaryKeyword: "best cheap vpn",
    intent: "commercial",
    cluster: "free-and-low-cost-access",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-best-vpn-cluster-2026-08-13.md", "/methodology", "/best/free-vpn"],
    affiliateContext: "vpn-selection",
    schemaType: "CollectionPage",
  },
  travel: {
    primaryKeyword: "vpn for travel",
    intent: "commercial",
    cluster: "travel-and-public-wifi",
    lastReviewedAt: "2026-08-12",
    evidence: ["docs/research/dataforseo-travel-cluster-2026-08-11.md", "/methodology", "https://www.cisa.gov/news-events/news/holiday-traveling-personal-internet-enabled-devices"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  restrictedNetworks: {
    primaryKeyword: "vpn on a restricted network",
    intent: "informational",
    cluster: "censorship-restricted-networks",
    lastReviewedAt: "2026-08-11",
    evidence: ["docs/research/dataforseo-restricted-networks-cluster-2026-08-11.md", "/methodology", "https://freedomhouse.org/"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  obfuscation: {
    primaryKeyword: "vpn obfuscation",
    intent: "informational",
    cluster: "protocol-and-technical-literacy",
    lastReviewedAt: "2026-08-11",
    evidence: ["docs/research/dataforseo-restricted-networks-cluster-2026-08-11.md", "/methodology", "https://www.wireguard.com/"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  protocols: {
    primaryKeyword: "vpn protocols",
    intent: "informational",
    cluster: "protocol-and-technical-literacy",
    lastReviewedAt: "2026-08-11",
    evidence: ["docs/research/dataforseo-protocols-cluster-2026-08-11.md", "/methodology", "https://www.wireguard.com/"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  russia: {
    primaryKeyword: "vpn for russia",
    intent: "commercial",
    cluster: "censorship-restricted-networks",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-russia-cluster-2026-08-13.md", "/methodology", "https://freedomhouse.org/country/russia/freedom-net/2025"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  telegram: {
    primaryKeyword: "best vpn for telegram",
    intent: "commercial",
    cluster: "censorship-restricted-networks",
    lastReviewedAt: "2026-08-12",
    evidence: ["docs/research/dataforseo-telegram-cluster-2026-08-11.md", "/methodology", "https://core.telegram.org/proxy"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  chatgpt: {
    primaryKeyword: "best vpn for chatgpt",
    intent: "commercial",
    cluster: "ai-privacy-and-access",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-chatgpt-vpn-cluster-2026-08-13.md", "/methodology", "https://help.openai.com/en/articles/7947663-chatgpt-supported-countries"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  redditFreeVpn: {
    primaryKeyword: "best free vpn reddit",
    intent: "commercial",
    cluster: "free-and-low-cost-access",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-reddit-free-vpn-cluster-2026-08-13.md", "/methodology", "/best/free-vpn"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  androidVpn: {
    primaryKeyword: "best vpn for android",
    intent: "commercial",
    cluster: "mobile-and-device-privacy",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-android-vpn-cluster-2026-08-13.md", "/methodology", "https://support.google.com/android/answer/9089766"],
    affiliateContext: "vpn-selection",
    schemaType: "CollectionPage",
  },
  chromebookVpn: {
    primaryKeyword: "best vpn for chromebook",
    intent: "informational",
    cluster: "mobile-and-device-privacy",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-chromebook-vpn-cluster-2026-08-13.md", "/methodology", "/best/vpn-android"],
    affiliateContext: "vpn-selection",
    schemaType: "CollectionPage",
  },
  firestickVpn: {
    primaryKeyword: "best vpn for firestick",
    intent: "informational",
    cluster: "mobile-and-device-privacy",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-firestick-vpn-cluster-2026-08-13.md", "/methodology", "/best/vpn-streaming"],
    affiliateContext: "vpn-selection",
    schemaType: "CollectionPage",
  },
} satisfies Record<string, EditorialContentBrief>;
