import type { EditorialContentBrief } from "@/lib/editorial-content-brief";

/** Shared briefs for the audited editorial cluster pages. */
export const editorialContentBriefs = {
  china: {
    primaryKeyword: "vpn for china",
    intent: "commercial",
    cluster: "censorship-restricted-networks",
    lastReviewedAt: "2026-08-11",
    evidence: ["docs/research/dataforseo-china-cluster-2026-08-11.md", "/methodology", "https://freedomhouse.org/country/china/freedom-net/2025"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  freeVpn: {
    primaryKeyword: "best free vpn",
    intent: "commercial",
    cluster: "free-and-low-cost-access",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-free-vpn-cluster-2026-08-13.md", "/methodology", "https://protonvpn.com/free-vpn/download"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  cheapVpn: {
    primaryKeyword: "best cheap vpn",
    intent: "commercial",
    cluster: "free-and-low-cost-access",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-best-vpn-cluster-2026-08-13.md", "/methodology", "/best/free-vpn"],
    affiliateContext: "vpn-selection",
    schemaType: "CollectionPage",
  },
  travel: {
    primaryKeyword: "vpn for travel",
    intent: "commercial",
    cluster: "travel-and-public-wifi",
    lastReviewedAt: "2026-08-12",
    evidence: ["docs/research/dataforseo-travel-cluster-2026-08-11.md", "/methodology", "https://www.cisa.gov/news-events/news/holiday-traveling-personal-internet-enabled-devices"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  restrictedNetworks: {
    primaryKeyword: "vpn on a restricted network",
    intent: "informational",
    cluster: "censorship-restricted-networks",
    lastReviewedAt: "2026-08-11",
    evidence: ["docs/research/dataforseo-restricted-networks-cluster-2026-08-11.md", "/methodology", "https://freedomhouse.org/"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  obfuscation: {
    primaryKeyword: "vpn obfuscation",
    intent: "informational",
    cluster: "protocol-and-technical-literacy",
    lastReviewedAt: "2026-08-11",
    evidence: ["docs/research/dataforseo-restricted-networks-cluster-2026-08-11.md", "/methodology", "https://www.wireguard.com/"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  protocols: {
    primaryKeyword: "vpn protocols",
    intent: "informational",
    cluster: "protocol-and-technical-literacy",
    lastReviewedAt: "2026-08-11",
    evidence: ["docs/research/dataforseo-protocols-cluster-2026-08-11.md", "/methodology", "https://www.wireguard.com/"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  russia: {
    primaryKeyword: "vpn for russia",
    intent: "commercial",
    cluster: "censorship-restricted-networks",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-russia-cluster-2026-08-13.md", "/methodology", "https://freedomhouse.org/country/russia/freedom-net/2025"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  vietnam: {
    primaryKeyword: "best vpn for vietnam",
    intent: "commercial",
    cluster: "censorship-restricted-networks",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-vietnam-cluster-2026-08-13.md", "/methodology", "https://freedomhouse.org/country/vietnam/freedom-net/2025", "https://www.hrw.org/world-report/2026/country-chapters/vietnam"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  telegram: {
    primaryKeyword: "best vpn for telegram",
    intent: "commercial",
    cluster: "censorship-restricted-networks",
    lastReviewedAt: "2026-08-12",
    evidence: ["docs/research/dataforseo-telegram-cluster-2026-08-11.md", "/methodology", "https://core.telegram.org/proxy"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  chatgpt: {
    primaryKeyword: "best vpn for chatgpt",
    intent: "commercial",
    cluster: "ai-privacy-and-access",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-chatgpt-vpn-cluster-2026-08-13.md", "/methodology", "https://help.openai.com/en/articles/7947663-chatgpt-supported-countries"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  redditFreeVpn: {
    primaryKeyword: "best free vpn reddit",
    intent: "commercial",
    cluster: "free-and-low-cost-access",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-reddit-free-vpn-cluster-2026-08-13.md", "/methodology", "/best/free-vpn"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  androidVpn: {
    primaryKeyword: "best vpn for android",
    intent: "commercial",
    cluster: "mobile-and-device-privacy",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-android-vpn-cluster-2026-08-13.md", "/methodology", "https://support.google.com/android/answer/9089766"],
    affiliateContext: "vpn-selection",
    schemaType: "CollectionPage",
  },
  androidTabletVpn: {
    primaryKeyword: "best vpn for android tablet",
    intent: "commercial",
    cluster: "mobile-and-device-privacy",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-android-tablet-vpn-cluster-2026-08-13.md", "/methodology", "https://support.google.com/android/answer/9089766", "https://developer.android.com/develop/connectivity/vpn"],
    affiliateContext: "vpn-selection",
    schemaType: "CollectionPage",
  },
  linuxVpn: {
    primaryKeyword: "best vpn for linux",
    intent: "commercial",
    cluster: "mobile-and-device-privacy",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-linux-vpn-cluster-2026-08-13.md", "/methodology", "https://nordvpn.com/download/linux/", "https://www.expressvpn.com/support/vpn-setup/app-for-linux/", "https://support.surfshark.com/hc/en-us/articles/5067279648146-How-to-set-up-Surfshark-VPN-on-Linux"],
    affiliateContext: "vpn-selection",
    schemaType: "CollectionPage",
  },
  chromebookVpn: {
    primaryKeyword: "best vpn for chromebook",
    intent: "informational",
    cluster: "mobile-and-device-privacy",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-chromebook-vpn-cluster-2026-08-13.md", "/methodology", "/best/vpn-android"],
    affiliateContext: "vpn-selection",
    schemaType: "CollectionPage",
  },
  firestickVpn: {
    primaryKeyword: "best vpn for firestick",
    intent: "informational",
    cluster: "mobile-and-device-privacy",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-firestick-vpn-cluster-2026-08-13.md", "/methodology", "/best/vpn-streaming"],
    affiliateContext: "vpn-selection",
    schemaType: "CollectionPage",
  },
  privacyVpn: {
    primaryKeyword: "best vpn for privacy",
    intent: "commercial",
    cluster: "privacy-and-trust",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-privacy-vpn-cluster-2026-08-13.md", "/methodology", "/guides/vpn-privacy-guide"],
    affiliateContext: "vpn-selection",
    schemaType: "CollectionPage",
  },
  gamingVpn: {
    primaryKeyword: "best vpn for gaming",
    intent: "commercial",
    cluster: "gaming-and-performance",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-gaming-cluster-2026-08-13.md", "/methodology", "/best/vpn-port-forwarding"],
    affiliateContext: "vpn-selection",
    schemaType: "CollectionPage",
  },
  vpnPingGaming: {
    primaryKeyword: "vpn reduce ping",
    intent: "informational",
    cluster: "gaming-and-performance",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-gaming-cluster-2026-08-13.md", "/methodology", "https://support.nordvpn.com/hc/en-us/articles/20280919698577-What-are-the-pros-and-cons-of-TCP-and-UDP"],
    affiliateContext: "none",
    schemaType: "Article",
  },
  speedTest: {
    primaryKeyword: "internet speed test",
    intent: "informational",
    cluster: "speed-and-performance",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-speed-test-cluster-2026-08-13.md", "https://developers.cloudflare.com/cloudflare-one/insights/dex/diagnostics/speed-test/", "/methodology"],
    affiliateContext: "none",
    schemaType: "Article",
  },
  dnsLeak: {
    primaryKeyword: "dns leak test",
    intent: "informational",
    cluster: "privacy-and-trust",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-dns-leak-cluster-2026-08-13.md", "/methodology", "https://browserleaks.com/dns", "https://protonvpn.com/support/dns-leaks-privacy"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  torrentingReddit: {
    primaryKeyword: "best vpn for torrenting reddit",
    intent: "commercial",
    cluster: "privacy-and-trust",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-torrenting-reddit-cluster-2026-08-13.md", "/methodology", "https://www.eff.org/issues/file-sharing", "https://protonvpn.com/support/port-forwarding"],
    affiliateContext: "none",
    schemaType: "Article",
  },
  portForwarding: {
    primaryKeyword: "best vpn with port forwarding",
    intent: "commercial",
    cluster: "gaming-and-performance",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-port-forwarding-cluster-2026-08-13.md", "/methodology", "https://protonvpn.com/support/port-forwarding", "https://support.nordvpn.com/hc/en-us/articles/19483392309649-Does-NordVPN-offer-port-forwarding"],
    affiliateContext: "vpn-selection",
    schemaType: "CollectionPage",
  },
  nordvpnReview: {
    primaryKeyword: "nordvpn review",
    intent: "commercial",
    cluster: "provider-reviews-and-comparisons",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-nordvpn-review-cluster-2026-08-13.md", "/methodology", "https://nordvpn.com/blog/nordvpn-no-logs-assurance-engagement-2025/", "https://support.nordvpn.com/hc/en-us/articles/19476991311121-What-is-your-money-back-policy"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  protonvpnReview: {
    primaryKeyword: "proton vpn review",
    intent: "commercial",
    cluster: "provider-reviews-and-comparisons",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-protonvpn-review-cluster-2026-08-13.md", "/methodology", "https://protonvpn.com/support/no-logs-vpn", "https://protonvpn.com/support/proton-vpn-free-plan"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  urbanVpnReview: {
    primaryKeyword: "urban vpn review",
    intent: "commercial",
    cluster: "provider-reviews-and-comparisons",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-urban-vpn-review-cluster-2026-08-13.md", "/methodology", "https://www.urban-vpn.com/privacy/", "https://www.koi.ai/blog/urban-vpn-browser-extension-ai-conversations-data-collection"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  surfsharkReview: {
    primaryKeyword: "surfshark review",
    intent: "commercial",
    cluster: "provider-reviews-and-comparisons",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-surfshark-review-cluster-2026-08-13.md", "/methodology", "https://surfshark.com/trust-center/no-logs", "https://surfshark.com/features/unlimited-devices"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  airvpnReview: {
    primaryKeyword: "airvpn review",
    intent: "commercial",
    cluster: "provider-reviews-and-comparisons",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-airvpn-review-cluster-2026-08-13.md", "/methodology", "https://airvpn.org/privacy/", "https://airvpn.org/faq/port_forwarding/"],
    affiliateContext: "vpn-selection",
    schemaType: "Article",
  },
  vpnComparison: {
    primaryKeyword: "vpn comparison",
    intent: "commercial",
    cluster: "provider-reviews-and-comparisons",
    lastReviewedAt: "2026-08-13",
    evidence: ["docs/research/dataforseo-vpn-comparison-cluster-2026-08-13.md", "/methodology", "/best/best-vpn"],
    affiliateContext: "vpn-selection",
    schemaType: "CollectionPage",
  },
} satisfies Record<string, EditorialContentBrief>;
