// Static VPN data for initial development (before database is set up)
// This can be replaced with database queries once Neon is configured

export interface VpnProvider {
  id: string;
  name: string;
  slug: string;
  logo: string;
  screenshot: string; // Hero screenshot of VPN website
  thumbnailImage: string; // Small thumbnail for cards
  cardImage: string; // Medium image for cards
  ogImage: string; // Social sharing image
  website: string;
  affiliateUrl: string;
  priceMonthly: number;
  priceYearly: number;
  priceTwoYear?: number;
  moneyBackDays: number;
  freeTier: boolean;
  servers: number;
  countries: number;
  maxDevices: number;
  speedScore: number;
  securityScore: number;
  streamingScore: number;
  protocols: string[];
  encryption: string;
  killSwitch: boolean;
  noLogs: boolean;
  netflixSupport: boolean;
  torrentSupport: boolean;
  overallRating: number;
  editorChoice: boolean;
  shortDescription: string;
  pros: string[];
  cons: string[];
  featured: boolean;
  sortOrder: number;
}

export const vpnProviders: VpnProvider[] = [
  {
    id: "nordvpn",
    name: "NordVPN",
    slug: "nordvpn",
    logo: "/logos/nordvpn.svg",
    screenshot: "/vpn-images/nordvpn-hero.webp",
    thumbnailImage: "/vpn-images/nordvpn-thumb.webp",
    cardImage: "/vpn-images/nordvpn-card.webp",
    ogImage: "/vpn-images/nordvpn-og.webp",
    website: "https://nordvpn.com",
    affiliateUrl: "https://go.zerotovpn.com/nordvpn",
    priceMonthly: 12.99,
    priceYearly: 4.99,
    priceTwoYear: 2.99,
    moneyBackDays: 30,
    freeTier: false,
    servers: 7400,
    countries: 118,
    maxDevices: 10,
    speedScore: 94,
    securityScore: 98,
    streamingScore: 95,
    protocols: ["WireGuard", "OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 4.8,
    editorChoice: true,
    shortDescription: "Industry-leading VPN with exceptional speed and security features.",
    pros: [
      "Excellent speeds with WireGuard protocol",
      "Huge server network (7,400+ servers)",
      "Advanced security features",
      "Works with Netflix and streaming",
      "Strict no-logs policy (audited)",
    ],
    cons: [
      "Slightly more expensive than competitors",
      "Occasional connectivity issues",
      "No free tier available",
    ],
    featured: true,
    sortOrder: 1,
  },
  {
    id: "surfshark",
    name: "Surfshark",
    slug: "surfshark",
    logo: "/logos/surfshark.svg",
    screenshot: "/vpn-images/surfshark-hero.webp",
    thumbnailImage: "/vpn-images/surfshark-thumb.webp",
    cardImage: "/vpn-images/surfshark-card.webp",
    ogImage: "/vpn-images/surfshark-og.webp",
    website: "https://surfshark.com",
    affiliateUrl: "https://go.zerotovpn.com/surfshark",
    priceMonthly: 15.45,
    priceYearly: 3.19,
    priceTwoYear: 1.99,
    moneyBackDays: 30,
    freeTier: false,
    servers: 4500,
    countries: 100,
    maxDevices: 999, // Unlimited
    speedScore: 90,
    securityScore: 95,
    streamingScore: 92,
    protocols: ["WireGuard", "OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 4.6,
    editorChoice: false,
    shortDescription: "Best value VPN with unlimited device connections.",
    pros: [
      "Unlimited simultaneous connections",
      "Very affordable long-term plans",
      "Good streaming support",
      "CleanWeb ad blocker included",
      "Camouflage mode for extra privacy",
    ],
    cons: [
      "Smaller server network",
      "Speeds can vary",
      "Based in the Netherlands (14 Eyes)",
    ],
    featured: true,
    sortOrder: 2,
  },
  {
    id: "expressvpn",
    name: "ExpressVPN",
    slug: "expressvpn",
    logo: "/logos/expressvpn.svg",
    screenshot: "/vpn-images/expressvpn-hero.webp",
    thumbnailImage: "/vpn-images/expressvpn-thumb.webp",
    cardImage: "/vpn-images/expressvpn-card.webp",
    ogImage: "/vpn-images/expressvpn-og.webp",
    website: "https://expressvpn.com",
    affiliateUrl: "https://go.zerotovpn.com/expressvpn",
    priceMonthly: 12.95,
    priceYearly: 8.32,
    moneyBackDays: 30,
    freeTier: false,
    servers: 3000,
    countries: 105,
    maxDevices: 8,
    speedScore: 96,
    securityScore: 97,
    streamingScore: 98,
    protocols: ["Lightway", "OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 4.7,
    editorChoice: false,
    shortDescription: "Premium VPN with fastest speeds and best streaming support.",
    pros: [
      "Fastest VPN speeds overall",
      "Best for streaming (works everywhere)",
      "Easy-to-use apps",
      "Excellent customer support",
      "TrustedServer technology",
    ],
    cons: [
      "Most expensive option",
      "Only 8 simultaneous connections",
      "No dedicated IP option",
    ],
    featured: true,
    sortOrder: 3,
  },
  {
    id: "cyberghost",
    name: "CyberGhost",
    slug: "cyberghost",
    logo: "/logos/cyberghost.svg",
    screenshot: "/vpn-images/cyberghost-hero.webp",
    thumbnailImage: "/vpn-images/cyberghost-thumb.webp",
    cardImage: "/vpn-images/cyberghost-card.webp",
    ogImage: "/vpn-images/cyberghost-og.webp",
    website: "https://cyberghostvpn.com",
    affiliateUrl: "https://go.zerotovpn.com/cyberghost",
    priceMonthly: 12.99,
    priceYearly: 4.29,
    priceTwoYear: 2.03,
    moneyBackDays: 45,
    freeTier: false,
    servers: 11690,
    countries: 100,
    maxDevices: 7,
    speedScore: 85,
    securityScore: 90,
    streamingScore: 88,
    protocols: ["WireGuard", "OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 4.4,
    editorChoice: false,
    shortDescription: "Largest server network with specialized streaming servers.",
    pros: [
      "Huge server network (11,000+)",
      "45-day money-back guarantee",
      "Dedicated streaming servers",
      "Very affordable",
      "User-friendly interface",
    ],
    cons: [
      "Slower speeds than competitors",
      "Owned by Kape Technologies",
      "Some servers are crowded",
    ],
    featured: true,
    sortOrder: 4,
  },
  {
    id: "protonvpn",
    name: "ProtonVPN",
    slug: "protonvpn",
    logo: "/logos/protonvpn.svg",
    screenshot: "/vpn-images/protonvpn-hero.webp",
    thumbnailImage: "/vpn-images/protonvpn-thumb.webp",
    cardImage: "/vpn-images/protonvpn-card.webp",
    ogImage: "/vpn-images/protonvpn-og.webp",
    website: "https://protonvpn.com",
    affiliateUrl: "https://go.zerotovpn.com/protonvpn",
    priceMonthly: 9.99,
    priceYearly: 4.99,
    priceTwoYear: 2.49,
    moneyBackDays: 30,
    freeTier: true,
    servers: 15000,
    countries: 120,
    maxDevices: 10,
    speedScore: 88,
    securityScore: 99,
    streamingScore: 80,
    protocols: ["WireGuard", "OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 4.5,
    editorChoice: false,
    shortDescription: "Swiss-based VPN with strongest privacy focus and free tier.",
    pros: [
      "Free tier available (no data limits)",
      "Based in privacy-friendly Switzerland",
      "Open source and audited",
      "Secure Core servers",
      "Integrates with ProtonMail",
    ],
    cons: [
      "Free tier has limited servers",
      "Streaming support is inconsistent",
      "Fewer server locations",
    ],
    featured: true,
    sortOrder: 5,
  },
  {
    id: "pia",
    name: "Private Internet Access",
    slug: "private-internet-access",
    logo: "/logos/pia.svg",
    screenshot: "/vpn-images/private-internet-access-hero.webp",
    thumbnailImage: "/vpn-images/private-internet-access-thumb.webp",
    cardImage: "/vpn-images/private-internet-access-card.webp",
    ogImage: "/vpn-images/private-internet-access-og.webp",
    website: "https://privateinternetaccess.com",
    affiliateUrl: "https://go.zerotovpn.com/private-internet-access",
    priceMonthly: 11.95,
    priceYearly: 3.33,
    priceTwoYear: 2.19,
    moneyBackDays: 30,
    freeTier: false,
    servers: 35000,
    countries: 91,
    maxDevices: 999,
    speedScore: 82,
    securityScore: 92,
    streamingScore: 75,
    protocols: ["WireGuard", "OpenVPN"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 4.3,
    editorChoice: false,
    shortDescription: "Veteran VPN with massive server network and proven no-logs policy.",
    pros: [
      "Massive server network (35,000+)",
      "Unlimited simultaneous connections",
      "Proven no-logs policy (court-tested)",
      "Very affordable",
      "Open source apps",
    ],
    cons: [
      "Based in the US (5 Eyes)",
      "Streaming support is hit or miss",
      "Dated interface on some apps",
    ],
    featured: false,
    sortOrder: 6,
  },
  {
    id: "mullvad",
    name: "Mullvad VPN",
    slug: "mullvad",
    logo: "/logos/mullvad.svg",
    screenshot: "/vpn-images/mullvad-hero.webp",
    thumbnailImage: "/vpn-images/mullvad-thumb.webp",
    cardImage: "/vpn-images/mullvad-card.webp",
    ogImage: "/vpn-images/mullvad-og.webp",
    website: "https://mullvad.net",
    affiliateUrl: "https://go.zerotovpn.com/mullvad",
    priceMonthly: 5.00,
    priceYearly: 5.00,
    moneyBackDays: 30,
    freeTier: false,
    servers: 800,
    countries: 43,
    maxDevices: 5,
    speedScore: 91,
    securityScore: 99,
    streamingScore: 60,
    protocols: ["WireGuard", "OpenVPN"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: false,
    torrentSupport: true,
    overallRating: 4.5,
    editorChoice: false,
    shortDescription: "Privacy-first VPN with anonymous account creation and flat pricing.",
    pros: [
      "No email required - account numbers only",
      "Accept cash payments for anonymity",
      "Simple flat pricing (€5/month)",
      "Excellent WireGuard implementation",
      "Independently audited",
    ],
    cons: [
      "Small server network",
      "No streaming optimization",
      "Limited to 5 devices",
      "Basic app interface",
    ],
    featured: false,
    sortOrder: 7,
  },
  {
    id: "ipvanish",
    name: "IPVanish",
    slug: "ipvanish",
    logo: "/logos/ipvanish.svg",
    screenshot: "/vpn-images/ipvanish-hero.webp",
    thumbnailImage: "/vpn-images/ipvanish-thumb.webp",
    cardImage: "/vpn-images/ipvanish-card.webp",
    ogImage: "/vpn-images/ipvanish-og.webp",
    website: "https://ipvanish.com",
    affiliateUrl: "https://go.zerotovpn.com/ipvanish",
    priceMonthly: 12.99,
    priceYearly: 3.99,
    moneyBackDays: 30,
    freeTier: false,
    servers: 2400,
    countries: 90,
    maxDevices: 999,
    speedScore: 85,
    securityScore: 88,
    streamingScore: 78,
    protocols: ["WireGuard", "OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 4.2,
    editorChoice: false,
    shortDescription: "US-based VPN with unlimited connections and Kodi support.",
    pros: [
      "Unlimited simultaneous connections",
      "Owns its entire server network",
      "Great for Kodi and Fire TV",
      "SOCKS5 proxy included",
      "Good speeds overall",
    ],
    cons: [
      "Based in the US (5 Eyes)",
      "Past privacy controversy",
      "Streaming can be unreliable",
      "Interface feels dated",
    ],
    featured: false,
    sortOrder: 8,
  },
  {
    id: "vyprvpn",
    name: "VyprVPN",
    slug: "vyprvpn",
    logo: "/logos/vyprvpn.svg",
    screenshot: "/vpn-images/vyprvpn-hero.webp",
    thumbnailImage: "/vpn-images/vyprvpn-thumb.webp",
    cardImage: "/vpn-images/vyprvpn-card.webp",
    ogImage: "/vpn-images/vyprvpn-og.webp",
    website: "https://vyprvpn.com",
    affiliateUrl: "https://go.zerotovpn.com/vyprvpn",
    priceMonthly: 15.00,
    priceYearly: 8.33,
    moneyBackDays: 30,
    freeTier: false,
    servers: 700,
    countries: 70,
    maxDevices: 10,
    speedScore: 83,
    securityScore: 90,
    streamingScore: 75,
    protocols: ["WireGuard", "OpenVPN", "Chameleon"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 4.1,
    editorChoice: false,
    shortDescription: "Swiss-based VPN with proprietary Chameleon protocol for censorship bypass.",
    pros: [
      "Owns 100% of server infrastructure",
      "Chameleon protocol defeats VPN blocks",
      "Based in privacy-friendly Switzerland",
      "Audited no-logs policy",
      "Works in China",
    ],
    cons: [
      "Smaller server network",
      "More expensive than competitors",
      "Speeds can vary",
      "Limited advanced features",
    ],
    featured: false,
    sortOrder: 9,
  },
  {
    id: "tunnelbear",
    name: "TunnelBear",
    slug: "tunnelbear",
    logo: "/logos/tunnelbear.svg",
    screenshot: "/vpn-images/tunnelbear-hero.webp",
    thumbnailImage: "/vpn-images/tunnelbear-thumb.webp",
    cardImage: "/vpn-images/tunnelbear-card.webp",
    ogImage: "/vpn-images/tunnelbear-og.webp",
    website: "https://tunnelbear.com",
    affiliateUrl: "https://go.zerotovpn.com/tunnelbear",
    priceMonthly: 9.99,
    priceYearly: 4.99,
    moneyBackDays: 0,
    freeTier: true,
    servers: 5000,
    countries: 47,
    maxDevices: 999,
    speedScore: 78,
    securityScore: 85,
    streamingScore: 65,
    protocols: ["OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: false,
    torrentSupport: false,
    overallRating: 3.9,
    editorChoice: false,
    shortDescription: "User-friendly VPN with cute bear theme and free tier option.",
    pros: [
      "Free tier with 2GB/month",
      "Very user-friendly interface",
      "Unlimited connections",
      "Independently audited annually",
      "Great for VPN beginners",
    ],
    cons: [
      "No refunds (free tier instead)",
      "Doesn't work with Netflix",
      "No P2P/torrenting support",
      "Owned by McAfee",
    ],
    featured: false,
    sortOrder: 10,
  },
  {
    id: "windscribe",
    name: "Windscribe",
    slug: "windscribe",
    logo: "/logos/windscribe.svg",
    screenshot: "/vpn-images/windscribe-hero.webp",
    thumbnailImage: "/vpn-images/windscribe-thumb.webp",
    cardImage: "/vpn-images/windscribe-card.webp",
    ogImage: "/vpn-images/windscribe-og.webp",
    website: "https://windscribe.com",
    affiliateUrl: "https://go.zerotovpn.com/windscribe",
    priceMonthly: 9.00,
    priceYearly: 5.75,
    moneyBackDays: 3,
    freeTier: true,
    servers: 700,
    countries: 69,
    maxDevices: 999,
    speedScore: 80,
    securityScore: 87,
    streamingScore: 82,
    protocols: ["WireGuard", "OpenVPN", "IKEv2", "Stealth"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 4.0,
    editorChoice: false,
    shortDescription: "Generous free tier VPN with 10GB/month and unlimited connections.",
    pros: [
      "Generous free tier (10GB/month)",
      "Unlimited simultaneous connections",
      "Built-in ad and malware blocker",
      "Flexible build-a-plan pricing",
      "Stealth protocol for censorship",
    ],
    cons: [
      "Only 3-day money-back guarantee",
      "Inconsistent speeds",
      "Smaller paid server network",
      "Based in Canada (5 Eyes)",
    ],
    featured: false,
    sortOrder: 11,
  },
  {
    id: "hotspotshield",
    name: "Hotspot Shield",
    slug: "hotspot-shield",
    logo: "/logos/hotspotshield.svg",
    screenshot: "/vpn-images/hotspot-shield-hero.webp",
    thumbnailImage: "/vpn-images/hotspot-shield-thumb.webp",
    cardImage: "/vpn-images/hotspot-shield-card.webp",
    ogImage: "/vpn-images/hotspot-shield-og.webp",
    website: "https://hotspotshield.com",
    affiliateUrl: "https://go.zerotovpn.com/hotspot-shield",
    priceMonthly: 12.99,
    priceYearly: 7.99,
    moneyBackDays: 45,
    freeTier: true,
    servers: 3200,
    countries: 80,
    maxDevices: 10,
    speedScore: 92,
    securityScore: 80,
    streamingScore: 85,
    protocols: ["Hydra", "OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: false,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 3.8,
    editorChoice: false,
    shortDescription: "Fast VPN with proprietary Hydra protocol and free tier.",
    pros: [
      "Very fast speeds (Hydra protocol)",
      "Free tier available",
      "45-day money-back guarantee",
      "Good for streaming",
      "Easy to use",
    ],
    cons: [
      "Logs some connection data",
      "Based in the US",
      "Free tier has ads",
      "Privacy concerns in past",
    ],
    featured: false,
    sortOrder: 12,
  },
  {
    id: "strongvpn",
    name: "StrongVPN",
    slug: "strongvpn",
    logo: "/logos/strongvpn.svg",
    screenshot: "/vpn-images/strongvpn-hero.webp",
    thumbnailImage: "/vpn-images/strongvpn-thumb.webp",
    cardImage: "/vpn-images/strongvpn-card.webp",
    ogImage: "/vpn-images/strongvpn-og.webp",
    website: "https://strongvpn.com",
    affiliateUrl: "https://go.zerotovpn.com/strongvpn",
    priceMonthly: 11.99,
    priceYearly: 3.97,
    moneyBackDays: 30,
    freeTier: false,
    servers: 950,
    countries: 46,
    maxDevices: 12,
    speedScore: 79,
    securityScore: 84,
    streamingScore: 80,
    protocols: ["WireGuard", "OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 3.7,
    editorChoice: false,
    shortDescription: "Long-standing VPN with focus on streaming and simplicity.",
    pros: [
      "Works with major streaming services",
      "12 simultaneous connections",
      "Simple and reliable",
      "Good customer support",
      "Affordable yearly plans",
    ],
    cons: [
      "Small server network",
      "Based in the US",
      "Basic feature set",
      "Outdated app design",
    ],
    featured: false,
    sortOrder: 13,
  },
  {
    id: "purevpn",
    name: "PureVPN",
    slug: "purevpn",
    logo: "/logos/purevpn.svg",
    screenshot: "/vpn-images/purevpn-hero.webp",
    thumbnailImage: "/vpn-images/purevpn-thumb.webp",
    cardImage: "/vpn-images/purevpn-card.webp",
    ogImage: "/vpn-images/purevpn-og.webp",
    website: "https://purevpn.com",
    affiliateUrl: "https://go.zerotovpn.com/purevpn",
    priceMonthly: 12.95,
    priceYearly: 3.24,
    priceTwoYear: 1.99,
    moneyBackDays: 31,
    freeTier: false,
    servers: 6500,
    countries: 78,
    maxDevices: 10,
    speedScore: 81,
    securityScore: 82,
    streamingScore: 83,
    protocols: ["WireGuard", "OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 3.9,
    editorChoice: false,
    shortDescription: "Feature-rich VPN with dedicated IPs and port forwarding.",
    pros: [
      "Dedicated IP addresses available",
      "Port forwarding supported",
      "Large server network",
      "Very affordable long-term",
      "31-day money-back guarantee",
    ],
    cons: [
      "Past privacy incidents",
      "Speeds can be inconsistent",
      "Some servers overcrowded",
      "Based in British Virgin Islands",
    ],
    featured: false,
    sortOrder: 14,
  },
  {
    id: "atlasvpn",
    name: "Atlas VPN",
    slug: "atlas-vpn",
    logo: "/logos/atlasvpn.svg",
    screenshot: "/vpn-images/atlas-vpn-hero.webp",
    thumbnailImage: "/vpn-images/atlas-vpn-thumb.webp",
    cardImage: "/vpn-images/atlas-vpn-card.webp",
    ogImage: "/vpn-images/atlas-vpn-og.webp",
    website: "https://atlasvpn.com",
    affiliateUrl: "https://go.zerotovpn.com/atlas-vpn",
    priceMonthly: 11.99,
    priceYearly: 3.29,
    priceTwoYear: 1.82,
    moneyBackDays: 30,
    freeTier: true,
    servers: 1000,
    countries: 49,
    maxDevices: 999,
    speedScore: 84,
    securityScore: 83,
    streamingScore: 80,
    protocols: ["WireGuard", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 3.8,
    editorChoice: false,
    shortDescription: "Budget-friendly VPN with free tier and unlimited devices.",
    pros: [
      "Very affordable pricing",
      "Unlimited simultaneous devices",
      "Free tier available",
      "Data breach monitor included",
      "Good streaming support",
    ],
    cons: [
      "Owned by Nord Security",
      "Smaller server network",
      "Free tier is limited",
      "Relatively new service",
    ],
    featured: false,
    sortOrder: 15,
  },
  {
    id: "privatevpn",
    name: "PrivateVPN",
    slug: "privatevpn",
    logo: "/logos/privatevpn.svg",
    screenshot: "/vpn-images/privatevpn-hero.webp",
    thumbnailImage: "/vpn-images/privatevpn-thumb.webp",
    cardImage: "/vpn-images/privatevpn-card.webp",
    ogImage: "/vpn-images/privatevpn-og.webp",
    website: "https://privatevpn.com",
    affiliateUrl: "https://go.zerotovpn.com/privatevpn",
    priceMonthly: 9.90,
    priceYearly: 3.82,
    moneyBackDays: 30,
    freeTier: false,
    servers: 200,
    countries: 63,
    maxDevices: 10,
    speedScore: 80,
    securityScore: 86,
    streamingScore: 88,
    protocols: ["OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 4.0,
    editorChoice: false,
    shortDescription: "Small but reliable VPN with excellent streaming support.",
    pros: [
      "Excellent streaming unblocking",
      "Based in privacy-friendly Sweden",
      "Port forwarding available",
      "Good customer support",
      "Stealth VPN for censorship",
    ],
    cons: [
      "Very small server network",
      "No WireGuard support",
      "No independent audit",
      "Limited advanced features",
    ],
    featured: false,
    sortOrder: 16,
  },
  {
    id: "torguard",
    name: "TorGuard",
    slug: "torguard",
    logo: "/logos/torguard.svg",
    screenshot: "/vpn-images/torguard-hero.webp",
    thumbnailImage: "/vpn-images/torguard-thumb.webp",
    cardImage: "/vpn-images/torguard-card.webp",
    ogImage: "/vpn-images/torguard-og.webp",
    website: "https://torguard.net",
    affiliateUrl: "https://go.zerotovpn.com/torguard",
    priceMonthly: 9.99,
    priceYearly: 4.99,
    moneyBackDays: 7,
    freeTier: false,
    servers: 3000,
    countries: 50,
    maxDevices: 12,
    speedScore: 85,
    securityScore: 88,
    streamingScore: 70,
    protocols: ["WireGuard", "OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: false,
    torrentSupport: true,
    overallRating: 4.0,
    editorChoice: false,
    shortDescription: "Privacy-focused VPN ideal for torrenting and P2P users.",
    pros: [
      "Excellent for torrenting",
      "Dedicated streaming IPs available",
      "Customizable encryption",
      "Good speeds",
      "Anonymous payment options",
    ],
    cons: [
      "Only 7-day money-back guarantee",
      "Streaming requires extra purchase",
      "Complex interface",
      "Based in the US",
    ],
    featured: false,
    sortOrder: 17,
  },
  {
    id: "airvpn",
    name: "AirVPN",
    slug: "airvpn",
    logo: "/logos/airvpn.svg",
    screenshot: "/vpn-images/airvpn-hero.webp",
    thumbnailImage: "/vpn-images/airvpn-thumb.webp",
    cardImage: "/vpn-images/airvpn-card.webp",
    ogImage: "/vpn-images/airvpn-og.webp",
    website: "https://airvpn.org",
    affiliateUrl: "https://go.zerotovpn.com/airvpn",
    priceMonthly: 7.00,
    priceYearly: 4.08,
    moneyBackDays: 3,
    freeTier: false,
    servers: 300,
    countries: 23,
    maxDevices: 5,
    speedScore: 82,
    securityScore: 91,
    streamingScore: 55,
    protocols: ["OpenVPN", "WireGuard"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: false,
    torrentSupport: true,
    overallRating: 3.8,
    editorChoice: false,
    shortDescription: "Technical VPN for power users with full transparency.",
    pros: [
      "Fully transparent operation",
      "Port forwarding included",
      "Real-time server stats",
      "Accept cryptocurrency",
      "Community-driven development",
    ],
    cons: [
      "Not beginner-friendly",
      "Small server network",
      "No streaming support",
      "Only 3-day refund policy",
    ],
    featured: false,
    sortOrder: 18,
  },
  {
    id: "ivpn",
    name: "IVPN",
    slug: "ivpn",
    logo: "/logos/ivpn.svg",
    screenshot: "/vpn-images/ivpn-hero.webp",
    thumbnailImage: "/vpn-images/ivpn-thumb.webp",
    cardImage: "/vpn-images/ivpn-card.webp",
    ogImage: "/vpn-images/ivpn-og.webp",
    website: "https://ivpn.net",
    affiliateUrl: "https://go.zerotovpn.com/ivpn",
    priceMonthly: 6.00,
    priceYearly: 5.00,
    moneyBackDays: 30,
    freeTier: false,
    servers: 100,
    countries: 37,
    maxDevices: 2,
    speedScore: 85,
    securityScore: 96,
    streamingScore: 50,
    protocols: ["WireGuard", "OpenVPN"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: false,
    torrentSupport: true,
    overallRating: 4.1,
    editorChoice: false,
    shortDescription: "Privacy-focused VPN with transparent practices and ethical approach.",
    pros: [
      "Extremely privacy-focused",
      "Transparent company practices",
      "No tracking or analytics",
      "Open source apps",
      "Multi-hop available",
    ],
    cons: [
      "Very small server network",
      "Only 2 devices on basic plan",
      "No streaming optimization",
      "More expensive per device",
    ],
    featured: false,
    sortOrder: 19,
  },
  {
    id: "mozillavpn",
    name: "Mozilla VPN",
    slug: "mozilla-vpn",
    logo: "/logos/mozillavpn.svg",
    screenshot: "/vpn-images/mozilla-vpn-hero.webp",
    thumbnailImage: "/vpn-images/mozilla-vpn-thumb.webp",
    cardImage: "/vpn-images/mozilla-vpn-card.webp",
    ogImage: "/vpn-images/mozilla-vpn-og.webp",
    website: "https://vpn.mozilla.org",
    affiliateUrl: "https://go.zerotovpn.com/mozilla-vpn",
    priceMonthly: 9.99,
    priceYearly: 4.99,
    moneyBackDays: 30,
    freeTier: false,
    servers: 500,
    countries: 30,
    maxDevices: 5,
    speedScore: 88,
    securityScore: 90,
    streamingScore: 60,
    protocols: ["WireGuard"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: false,
    torrentSupport: true,
    overallRating: 4.0,
    editorChoice: false,
    shortDescription: "Simple VPN from Mozilla using Mullvad's network infrastructure.",
    pros: [
      "Backed by trusted Mozilla",
      "Uses Mullvad's secure network",
      "WireGuard only (fast)",
      "Simple and clean interface",
      "Strong privacy commitment",
    ],
    cons: [
      "Limited server locations",
      "No streaming support",
      "Only 5 devices",
      "Not available everywhere",
    ],
    featured: false,
    sortOrder: 20,
  },
  {
    id: "hideme",
    name: "Hide.me",
    slug: "hide-me",
    logo: "/logos/hideme.svg",
    screenshot: "/vpn-images/hide-me-hero.webp",
    thumbnailImage: "/vpn-images/hide-me-thumb.webp",
    cardImage: "/vpn-images/hide-me-card.webp",
    ogImage: "/vpn-images/hide-me-og.webp",
    website: "https://hide.me",
    affiliateUrl: "https://go.zerotovpn.com/hide-me",
    priceMonthly: 9.95,
    priceYearly: 4.57,
    priceTwoYear: 2.59,
    moneyBackDays: 30,
    freeTier: true,
    servers: 2400,
    countries: 89,
    maxDevices: 10,
    speedScore: 84,
    securityScore: 89,
    streamingScore: 75,
    protocols: ["WireGuard", "OpenVPN", "IKEv2", "SoftEther"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 4.1,
    editorChoice: false,
    shortDescription: "Malaysian VPN with strong privacy focus and free tier.",
    pros: [
      "Generous free tier (10GB)",
      "Based in Malaysia (no data retention)",
      "Multiple protocol options",
      "Independent security audit",
      "Good speeds overall",
    ],
    cons: [
      "Free plan is limited",
      "Not the fastest option",
      "Interface could be better",
      "Streaming is hit or miss",
    ],
    featured: false,
    sortOrder: 21,
  },
  {
    id: "zenmate",
    name: "ZenMate VPN",
    slug: "zenmate",
    logo: "/logos/zenmate.svg",
    screenshot: "/vpn-images/zenmate-hero.webp",
    thumbnailImage: "/vpn-images/zenmate-thumb.webp",
    cardImage: "/vpn-images/zenmate-card.webp",
    ogImage: "/vpn-images/zenmate-og.webp",
    website: "https://zenmate.com",
    affiliateUrl: "https://go.zerotovpn.com/zenmate",
    priceMonthly: 10.99,
    priceYearly: 2.22,
    moneyBackDays: 30,
    freeTier: false,
    servers: 4800,
    countries: 81,
    maxDevices: 999,
    speedScore: 78,
    securityScore: 80,
    streamingScore: 82,
    protocols: ["OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 3.6,
    editorChoice: false,
    shortDescription: "German VPN with unlimited connections and affordable pricing.",
    pros: [
      "Unlimited simultaneous connections",
      "Very affordable yearly plan",
      "Dedicated streaming servers",
      "Easy to use apps",
      "Based in Germany",
    ],
    cons: [
      "Owned by Kape Technologies",
      "No WireGuard support",
      "Slower than competitors",
      "Limited advanced features",
    ],
    featured: false,
    sortOrder: 22,
  },
  {
    id: "privadovpn",
    name: "PrivadoVPN",
    slug: "privadovpn",
    logo: "/logos/privadovpn.svg",
    screenshot: "/vpn-images/privadovpn-hero.webp",
    thumbnailImage: "/vpn-images/privadovpn-thumb.webp",
    cardImage: "/vpn-images/privadovpn-card.webp",
    ogImage: "/vpn-images/privadovpn-og.webp",
    website: "https://privadovpn.com",
    affiliateUrl: "https://go.zerotovpn.com/privadovpn",
    priceMonthly: 10.99,
    priceYearly: 2.50,
    priceTwoYear: 1.99,
    moneyBackDays: 30,
    freeTier: true,
    servers: 350,
    countries: 66,
    maxDevices: 10,
    speedScore: 82,
    securityScore: 85,
    streamingScore: 78,
    protocols: ["WireGuard", "OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 3.9,
    editorChoice: false,
    shortDescription: "Swiss-based VPN with generous free tier and competitive pricing.",
    pros: [
      "Free tier with 10GB/month",
      "Based in Switzerland",
      "Very affordable paid plans",
      "SOCKS5 proxy included",
      "Ad blocker included",
    ],
    cons: [
      "Small server network",
      "Free version is slow",
      "Relatively unknown brand",
      "Limited server locations",
    ],
    featured: false,
    sortOrder: 23,
  },
  {
    id: "hma",
    name: "HMA VPN",
    slug: "hma",
    logo: "/logos/hma.svg",
    screenshot: "/vpn-images/hma-hero.webp",
    thumbnailImage: "/vpn-images/hma-thumb.webp",
    cardImage: "/vpn-images/hma-card.webp",
    ogImage: "/vpn-images/hma-og.webp",
    website: "https://hidemyass.com",
    affiliateUrl: "https://go.zerotovpn.com/hma",
    priceMonthly: 12.99,
    priceYearly: 4.99,
    priceTwoYear: 2.99,
    moneyBackDays: 30,
    freeTier: false,
    servers: 1080,
    countries: 210,
    maxDevices: 5,
    speedScore: 80,
    securityScore: 78,
    streamingScore: 75,
    protocols: ["OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: false,
    netflixSupport: true,
    torrentSupport: false,
    overallRating: 3.5,
    editorChoice: false,
    shortDescription: "VPN with servers in most countries worldwide (210+ locations).",
    pros: [
      "Servers in 210+ countries",
      "Easy to use interface",
      "IP shuffle feature",
      "Smart Kill Switch",
      "Owned by Avast",
    ],
    cons: [
      "Keeps some connection logs",
      "No torrenting support",
      "Past privacy incidents",
      "Based in the UK (5 Eyes)",
    ],
    featured: false,
    sortOrder: 24,
  },
  {
    id: "astrillvpn",
    name: "Astrill VPN",
    slug: "astrill",
    logo: "/logos/astrill.svg",
    screenshot: "/vpn-images/astrill-hero.webp",
    thumbnailImage: "/vpn-images/astrill-thumb.webp",
    cardImage: "/vpn-images/astrill-card.webp",
    ogImage: "/vpn-images/astrill-og.webp",
    website: "https://astrill.com",
    affiliateUrl: "https://go.zerotovpn.com/astrill",
    priceMonthly: 30.00,
    priceYearly: 12.50,
    moneyBackDays: 7,
    freeTier: false,
    servers: 300,
    countries: 56,
    maxDevices: 5,
    speedScore: 75,
    securityScore: 85,
    streamingScore: 70,
    protocols: ["OpenVPN", "WireGuard", "StealthVPN", "OpenWeb"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 3.7,
    editorChoice: false,
    shortDescription: "Premium VPN known for working reliably in China.",
    pros: [
      "Works in China (StealthVPN)",
      "Multiple proprietary protocols",
      "Smart mode for speed",
      "VIP addon for dedicated IPs",
      "Router app available",
    ],
    cons: [
      "Very expensive",
      "Only 7-day money-back",
      "Outdated interface",
      "Inconsistent speeds",
    ],
    featured: false,
    sortOrder: 25,
  },
  {
    id: "perfectprivacy",
    name: "Perfect Privacy",
    slug: "perfect-privacy",
    logo: "/logos/perfectprivacy.svg",
    screenshot: "/vpn-images/perfect-privacy-hero.webp",
    thumbnailImage: "/vpn-images/perfect-privacy-thumb.webp",
    cardImage: "/vpn-images/perfect-privacy-card.webp",
    ogImage: "/vpn-images/perfect-privacy-og.webp",
    website: "https://perfect-privacy.com",
    affiliateUrl: "https://go.zerotovpn.com/perfect-privacy",
    priceMonthly: 12.99,
    priceYearly: 9.99,
    priceTwoYear: 8.95,
    moneyBackDays: 7,
    freeTier: false,
    servers: 55,
    countries: 25,
    maxDevices: 999,
    speedScore: 80,
    securityScore: 95,
    streamingScore: 55,
    protocols: ["OpenVPN", "IPSec", "SSH"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: false,
    torrentSupport: true,
    overallRating: 3.8,
    editorChoice: false,
    shortDescription: "Premium privacy VPN with multi-hop and NeuroRouting.",
    pros: [
      "Unlimited simultaneous connections",
      "Multi-hop cascading",
      "NeuroRouting technology",
      "TrackStop filter",
      "Port forwarding on all servers",
    ],
    cons: [
      "Very small server network",
      "Expensive",
      "No streaming support",
      "Complex for beginners",
    ],
    featured: false,
    sortOrder: 26,
  },
  {
    id: "goosevpn",
    name: "Goose VPN",
    slug: "goose-vpn",
    logo: "/logos/goosevpn.svg",
    screenshot: "/vpn-images/goose-vpn-hero.webp",
    thumbnailImage: "/vpn-images/goose-vpn-thumb.webp",
    cardImage: "/vpn-images/goose-vpn-card.webp",
    ogImage: "/vpn-images/goose-vpn-og.webp",
    website: "https://goosevpn.com",
    affiliateUrl: "https://go.zerotovpn.com/goose-vpn",
    priceMonthly: 12.99,
    priceYearly: 2.99,
    moneyBackDays: 30,
    freeTier: false,
    servers: 130,
    countries: 30,
    maxDevices: 999,
    speedScore: 72,
    securityScore: 78,
    streamingScore: 70,
    protocols: ["OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 3.4,
    editorChoice: false,
    shortDescription: "Dutch VPN with unlimited connections and simple interface.",
    pros: [
      "Unlimited simultaneous devices",
      "Based in Netherlands",
      "Very affordable yearly",
      "Simple interface",
      "Cyber Alarm feature",
    ],
    cons: [
      "Very small server network",
      "Slow speeds",
      "Limited features",
      "Netherlands (EU data laws)",
    ],
    featured: false,
    sortOrder: 27,
  },
  {
    id: "trustzone",
    name: "Trust.Zone",
    slug: "trust-zone",
    logo: "/logos/trustzone.svg",
    screenshot: "/vpn-images/trust-zone-hero.webp",
    thumbnailImage: "/vpn-images/trust-zone-thumb.webp",
    cardImage: "/vpn-images/trust-zone-card.webp",
    ogImage: "/vpn-images/trust-zone-og.webp",
    website: "https://trust.zone",
    affiliateUrl: "https://go.zerotovpn.com/trust-zone",
    priceMonthly: 8.88,
    priceYearly: 3.33,
    priceTwoYear: 2.33,
    moneyBackDays: 10,
    freeTier: true,
    servers: 200,
    countries: 107,
    maxDevices: 5,
    speedScore: 77,
    securityScore: 82,
    streamingScore: 65,
    protocols: ["WireGuard", "OpenVPN", "L2TP"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 3.5,
    editorChoice: false,
    shortDescription: "Seychelles-based VPN with no-logs policy and Bitcoin support.",
    pros: [
      "Based in Seychelles (privacy-friendly)",
      "Accepts Bitcoin payments",
      "Very affordable",
      "Free trial available",
      "Port forwarding available",
    ],
    cons: [
      "Small server network",
      "Only 10-day money-back",
      "Limited customer support",
      "Basic app features",
    ],
    featured: false,
    sortOrder: 28,
  },
  {
    id: "fastestvpn",
    name: "FastestVPN",
    slug: "fastestvpn",
    logo: "/logos/fastestvpn.svg",
    screenshot: "/vpn-images/fastestvpn-hero.webp",
    thumbnailImage: "/vpn-images/fastestvpn-thumb.webp",
    cardImage: "/vpn-images/fastestvpn-card.webp",
    ogImage: "/vpn-images/fastestvpn-og.webp",
    website: "https://fastestvpn.com",
    affiliateUrl: "https://go.zerotovpn.com/fastestvpn",
    priceMonthly: 10.00,
    priceYearly: 2.49,
    priceTwoYear: 1.11,
    moneyBackDays: 31,
    freeTier: false,
    servers: 800,
    countries: 52,
    maxDevices: 10,
    speedScore: 78,
    securityScore: 80,
    streamingScore: 75,
    protocols: ["WireGuard", "OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 3.6,
    editorChoice: false,
    shortDescription: "Budget VPN with lifetime plans and NAT firewall.",
    pros: [
      "Lifetime subscription available",
      "Very affordable",
      "NAT firewall included",
      "Ad blocker included",
      "10 simultaneous connections",
    ],
    cons: [
      "Not the fastest despite name",
      "Cayman Islands jurisdiction",
      "Small server network",
      "Limited advanced features",
    ],
    featured: false,
    sortOrder: 29,
  },
  {
    id: "ovpn",
    name: "OVPN",
    slug: "ovpn",
    logo: "/logos/ovpn.svg",
    screenshot: "/vpn-images/ovpn-hero.webp",
    thumbnailImage: "/vpn-images/ovpn-thumb.webp",
    cardImage: "/vpn-images/ovpn-card.webp",
    ogImage: "/vpn-images/ovpn-og.webp",
    website: "https://ovpn.com",
    affiliateUrl: "https://go.zerotovpn.com/ovpn",
    priceMonthly: 11.00,
    priceYearly: 4.99,
    moneyBackDays: 10,
    freeTier: false,
    servers: 102,
    countries: 32,
    maxDevices: 6,
    speedScore: 87,
    securityScore: 93,
    streamingScore: 70,
    protocols: ["WireGuard", "OpenVPN"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 4.0,
    editorChoice: false,
    shortDescription: "Swedish VPN with physical servers only and strong privacy.",
    pros: [
      "Physical servers only (no virtual)",
      "Based in privacy-friendly Sweden",
      "Proven in court (no logs)",
      "Multi-hop available",
      "DNS leak protection",
    ],
    cons: [
      "Very small server network",
      "Only 10-day refund",
      "More expensive",
      "Limited server locations",
    ],
    featured: false,
    sortOrder: 30,
  },
  {
    id: "cactus",
    name: "CactusVPN",
    slug: "cactusvpn",
    logo: "/logos/cactusvpn.svg",
    screenshot: "/vpn-images/cactusvpn-hero.webp",
    thumbnailImage: "/vpn-images/cactusvpn-thumb.webp",
    cardImage: "/vpn-images/cactusvpn-card.webp",
    ogImage: "/vpn-images/cactusvpn-og.webp",
    website: "https://cactusvpn.com",
    affiliateUrl: "https://go.zerotovpn.com/cactusvpn",
    priceMonthly: 6.99,
    priceYearly: 3.25,
    priceTwoYear: 2.77,
    moneyBackDays: 30,
    freeTier: true,
    servers: 39,
    countries: 22,
    maxDevices: 999,
    speedScore: 75,
    securityScore: 82,
    streamingScore: 80,
    protocols: ["WireGuard", "OpenVPN", "IKEv2", "SSTP", "L2TP"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 3.5,
    editorChoice: false,
    shortDescription: "Moldova-based VPN with Smart DNS and free trial.",
    pros: [
      "Free trial available",
      "Smart DNS included",
      "Unlimited devices",
      "Based in Moldova",
      "Affordable pricing",
    ],
    cons: [
      "Very small server network",
      "Inconsistent speeds",
      "Limited locations",
      "Not well known",
    ],
    featured: false,
    sortOrder: 31,
  },
  {
    id: "betternet",
    name: "Betternet",
    slug: "betternet",
    logo: "/logos/betternet.svg",
    screenshot: "/vpn-images/betternet-hero.webp",
    thumbnailImage: "/vpn-images/betternet-thumb.webp",
    cardImage: "/vpn-images/betternet-card.webp",
    ogImage: "/vpn-images/betternet-og.webp",
    website: "https://betternet.co",
    affiliateUrl: "https://go.zerotovpn.com/betternet",
    priceMonthly: 12.99,
    priceYearly: 7.99,
    moneyBackDays: 45,
    freeTier: true,
    servers: 100,
    countries: 10,
    maxDevices: 10,
    speedScore: 65,
    securityScore: 65,
    streamingScore: 55,
    protocols: ["Catapult Hydra", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: false,
    netflixSupport: false,
    torrentSupport: false,
    overallRating: 3.0,
    editorChoice: false,
    shortDescription: "Simple free VPN with basic features for casual users.",
    pros: [
      "Free tier available",
      "45-day money-back guarantee",
      "Very easy to use",
      "Good for beginners",
      "No registration required",
    ],
    cons: [
      "Logs connection data",
      "Slow speeds",
      "No streaming support",
      "No torrenting",
    ],
    featured: false,
    sortOrder: 32,
  },
  {
    id: "speedify",
    name: "Speedify",
    slug: "speedify",
    logo: "/logos/speedify.svg",
    screenshot: "/vpn-images/speedify-hero.webp",
    thumbnailImage: "/vpn-images/speedify-thumb.webp",
    cardImage: "/vpn-images/speedify-card.webp",
    ogImage: "/vpn-images/speedify-og.webp",
    website: "https://speedify.com",
    affiliateUrl: "https://go.zerotovpn.com/speedify",
    priceMonthly: 14.99,
    priceYearly: 5.99,
    moneyBackDays: 30,
    freeTier: true,
    servers: 1200,
    countries: 60,
    maxDevices: 5,
    speedScore: 89,
    securityScore: 80,
    streamingScore: 78,
    protocols: ["OpenVPN", "Custom"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 3.8,
    editorChoice: false,
    shortDescription: "Unique VPN that bonds multiple internet connections for speed.",
    pros: [
      "Channel bonding technology",
      "Combines multiple connections",
      "Good for streaming",
      "Free tier (2GB/month)",
      "Automatic failover",
    ],
    cons: [
      "Needs multiple connections to excel",
      "More expensive",
      "Not privacy-focused",
      "Based in US",
    ],
    featured: false,
    sortOrder: 33,
  },
  {
    id: "vpnunlimited",
    name: "VPN Unlimited",
    slug: "vpn-unlimited",
    logo: "/logos/vpnunlimited.svg",
    screenshot: "/vpn-images/vpn-unlimited-hero.webp",
    thumbnailImage: "/vpn-images/vpn-unlimited-thumb.webp",
    cardImage: "/vpn-images/vpn-unlimited-card.webp",
    ogImage: "/vpn-images/vpn-unlimited-og.webp",
    website: "https://vpnunlimitedapp.com",
    affiliateUrl: "https://go.zerotovpn.com/vpn-unlimited",
    priceMonthly: 9.99,
    priceYearly: 5.00,
    moneyBackDays: 30,
    freeTier: true,
    servers: 3000,
    countries: 80,
    maxDevices: 5,
    speedScore: 78,
    securityScore: 82,
    streamingScore: 80,
    protocols: ["WireGuard", "OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 3.7,
    editorChoice: false,
    shortDescription: "KeepSolid VPN with lifetime plans and personal server option.",
    pros: [
      "Lifetime subscription available",
      "Personal server option",
      "Good streaming support",
      "Trusted developer (KeepSolid)",
      "7-day free trial",
    ],
    cons: [
      "Based in US",
      "Only 5 devices",
      "Confusing pricing",
      "Speeds can vary",
    ],
    featured: false,
    sortOrder: 34,
  },
  {
    id: "nordlayer",
    name: "NordLayer",
    slug: "nordlayer",
    logo: "/logos/nordlayer.svg",
    screenshot: "/vpn-images/nordlayer-hero.webp",
    thumbnailImage: "/vpn-images/nordlayer-thumb.webp",
    cardImage: "/vpn-images/nordlayer-card.webp",
    ogImage: "/vpn-images/nordlayer-og.webp",
    website: "https://nordlayer.com",
    affiliateUrl: "https://go.zerotovpn.com/nordlayer",
    priceMonthly: 8.00,
    priceYearly: 6.00,
    moneyBackDays: 14,
    freeTier: false,
    servers: 60,
    countries: 33,
    maxDevices: 6,
    speedScore: 88,
    securityScore: 94,
    streamingScore: 50,
    protocols: ["WireGuard", "OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: false,
    torrentSupport: false,
    overallRating: 4.1,
    editorChoice: false,
    shortDescription: "Business VPN by Nord Security for teams and organizations.",
    pros: [
      "Built for businesses",
      "Team management features",
      "Dedicated IP available",
      "Site-to-site connectivity",
      "Strong security focus",
    ],
    cons: [
      "Not for personal use",
      "Per-user pricing",
      "No streaming features",
      "Limited server network",
    ],
    featured: false,
    sortOrder: 35,
  },
  {
    id: "perimeterjv",
    name: "Perimeter 81",
    slug: "perimeter-81",
    logo: "/logos/perimeter81.svg",
    screenshot: "/vpn-images/perimeter-81-hero.webp",
    thumbnailImage: "/vpn-images/perimeter-81-thumb.webp",
    cardImage: "/vpn-images/perimeter-81-card.webp",
    ogImage: "/vpn-images/perimeter-81-og.webp",
    website: "https://perimeter81.com",
    affiliateUrl: "https://go.zerotovpn.com/perimeter-81",
    priceMonthly: 10.00,
    priceYearly: 8.00,
    moneyBackDays: 30,
    freeTier: false,
    servers: 700,
    countries: 50,
    maxDevices: 5,
    speedScore: 85,
    securityScore: 95,
    streamingScore: 45,
    protocols: ["WireGuard", "OpenVPN", "IPSec"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: true,
    netflixSupport: false,
    torrentSupport: false,
    overallRating: 4.0,
    editorChoice: false,
    shortDescription: "Enterprise-grade SASE platform with zero-trust network access.",
    pros: [
      "Zero Trust architecture",
      "Enterprise security features",
      "Centralized management",
      "Split tunneling",
      "SSO integration",
    ],
    cons: [
      "Enterprise pricing",
      "Not for individual use",
      "No consumer features",
      "Complex setup",
    ],
    featured: false,
    sortOrder: 36,
  },
  {
    id: "urbanvpn",
    name: "Urban VPN",
    slug: "urban-vpn",
    logo: "/logos/urbanvpn.svg",
    screenshot: "/vpn-images/urban-vpn-hero.webp",
    thumbnailImage: "/vpn-images/urban-vpn-thumb.webp",
    cardImage: "/vpn-images/urban-vpn-card.webp",
    ogImage: "/vpn-images/urban-vpn-og.webp",
    website: "https://urban-vpn.com",
    affiliateUrl: "https://go.zerotovpn.com/urban-vpn",
    priceMonthly: 0,
    priceYearly: 0,
    moneyBackDays: 0,
    freeTier: true,
    servers: 80,
    countries: 81,
    maxDevices: 999,
    speedScore: 60,
    securityScore: 55,
    streamingScore: 50,
    protocols: ["OpenVPN"],
    encryption: "AES-256",
    killSwitch: false,
    noLogs: false,
    netflixSupport: false,
    torrentSupport: false,
    overallRating: 2.5,
    editorChoice: false,
    shortDescription: "Free peer-to-peer VPN with basic features.",
    pros: [
      "Completely free",
      "No registration required",
      "Available in many countries",
      "Unlimited data",
      "Simple to use",
    ],
    cons: [
      "Uses P2P network (your IP shared)",
      "Very slow speeds",
      "Privacy concerns",
      "No advanced features",
    ],
    featured: false,
    sortOrder: 37,
  },
  {
    id: "rayvpn",
    name: "X-VPN",
    slug: "x-vpn",
    logo: "/logos/xvpn.svg",
    screenshot: "/vpn-images/x-vpn-hero.webp",
    thumbnailImage: "/vpn-images/x-vpn-thumb.webp",
    cardImage: "/vpn-images/x-vpn-card.webp",
    ogImage: "/vpn-images/x-vpn-og.webp",
    website: "https://xvpn.io",
    affiliateUrl: "https://go.zerotovpn.com/x-vpn",
    priceMonthly: 11.99,
    priceYearly: 5.99,
    moneyBackDays: 30,
    freeTier: true,
    servers: 8000,
    countries: 60,
    maxDevices: 5,
    speedScore: 75,
    securityScore: 70,
    streamingScore: 72,
    protocols: ["OpenVPN", "IKEv2"],
    encryption: "AES-256",
    killSwitch: true,
    noLogs: false,
    netflixSupport: true,
    torrentSupport: true,
    overallRating: 3.2,
    editorChoice: false,
    shortDescription: "Mobile-first VPN with free tier and one-tap connection.",
    pros: [
      "Free tier available",
      "8000+ servers",
      "One-tap connection",
      "Good mobile apps",
      "Works in China",
    ],
    cons: [
      "Logs some data",
      "Hong Kong-based",
      "Slow free version",
      "Privacy policy concerns",
    ],
    featured: false,
    sortOrder: 38,
  },
];

export function getVpnBySlug(slug: string): VpnProvider | undefined {
  return vpnProviders.find((vpn) => vpn.slug === slug);
}

export function getFeaturedVpns(): VpnProvider[] {
  return vpnProviders.filter((vpn) => vpn.featured).sort((a, b) => a.sortOrder - b.sortOrder);
}

export function getAllVpns(): VpnProvider[] {
  return vpnProviders.sort((a, b) => a.sortOrder - b.sortOrder);
}
