import { AlertTriangle, CheckCircle2, CircleHelp, Lock, ShieldCheck } from "lucide-react";
import { Link } from "@/i18n/navigation";
import { AffiliateButton, AffiliateTextLink } from "@/components/vpn/affiliate-button";
import { FAQSchema } from "@/components/seo/faq-schema";
import { BreadcrumbSchema } from "@/components/seo/breadcrumb-schema";
import { BestVpnEditorialTemplate } from "@/components/editorial/best-vpn-editorial-template";
import { DnsLeakWidget } from "@/components/tools/dns-leak-widget";
import { getVpnById } from "@/lib/vpn-data";
import { getVpnAffiliateUrl, type VpnLinkSlug } from "@/lib/vpn-links";
import { editorialContentBriefs } from "@/lib/editorial-content-briefs";

export const dnsLeakEditorialTitle = "DNS Leak Test: Check Whether Your VPN Is Routing DNS Correctly";
export const dnsLeakEditorialDescription = "Run a browser-based DNS leak test, then learn how to interpret resolver ownership, IPv6, browser DNS settings and VPN-client routing without treating one result as a complete privacy audit.";

export const dnsLeakEditorialFaq = [
  { question: "What is a DNS leak?", answer: "A DNS leak happens when a device sends a domain lookup outside the encrypted path you intended to use, such as to an ISP resolver while a VPN is connected. The result can reveal resolver or network context even when your public IP is different." },
  { question: "How can I check if my VPN has a DNS leak?", answer: "Run the test before and after connecting the VPN, compare the listed resolver organisations and locations, and repeat it on Wi-Fi and mobile data. A single browser result cannot verify every app, IPv6 path or split-tunnel rule." },
  { question: "Can a DNS leak expose my location?", answer: "It can expose information about the network or resolver handling your queries. Treat the location as an indicator, not a precise GPS result; DNS, IP, browser and account signals can disagree." },
  { question: "How do I fix a DNS leak?", answer: "Check the VPN app's DNS and kill-switch settings, remove unexpected custom DNS entries, review browser Secure DNS or DoH settings, and test IPv4 and IPv6 again. Follow the provider's current support steps for your device." },
  { question: "Is a DNS leak test safe?", answer: "A normal test performs DNS lookups for test domains and reports the resolvers that answer. Use a reputable test, avoid entering credentials, and read its privacy policy before relying on it." },
  { question: "Does a DNS leak test prove that a VPN is private?", answer: "No. It checks one part of the network path. It does not audit the provider's logging, app permissions, WebRTC behaviour, account telemetry or the privacy of the destination websites you use." },
];

const providers = [
  { id: "nordvpn", label: "NordVPN", angle: "Check the app's DNS, kill-switch and protocol settings against the current support documentation" },
  { id: "surfshark", label: "Surfshark", angle: "Compare the device-specific routing and custom-DNS guidance before relying on the tunnel" },
  { id: "expressvpn", label: "ExpressVPN", angle: "Use the provider's current leak-protection instructions as a second source of verification" },
] as const satisfies ReadonlyArray<{ id: VpnLinkSlug; label: string; angle: string }>;

function ProviderCard({ provider }: { provider: (typeof providers)[number] }) {
  const vpn = getVpnById(provider.id);
  if (!vpn) return null;
  const affiliateUrl = getVpnAffiliateUrl(provider.id);
  const price = vpn.priceTwoYear ?? vpn.priceYearly;
  return <article className="rounded-xl border bg-card p-5 shadow-sm"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Privacy option to verify</p><h3 className="mt-2 text-xl font-semibold">{provider.label}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{provider.angle}.</p><p className="mt-4 text-2xl font-bold text-primary"><AffiliateTextLink vpnId={vpn.id} vpnName={vpn.name} affiliateUrl={affiliateUrl} dataPriceLink>${price.toFixed(2)}</AffiliateTextLink><span className="ml-1 text-sm font-normal text-muted-foreground">/mo equivalent</span></p><p className="mt-1 text-xs text-muted-foreground">Catalog snapshot checked {vpn.priceLastVerified ?? "date not recorded"}; verify current terms.</p><AffiliateButton vpnId={vpn.id} vpnName={vpn.name} affiliateUrl={affiliateUrl} className="mt-4 w-full">Check {provider.label} privacy options</AffiliateButton></article>;
}

export function DnsLeakEditorialPage() {
  return <BestVpnEditorialTemplate brief={editorialContentBriefs.dnsLeak} navigation={[{ href: "#test", label: "Test" }, { href: "#interpret", label: "Interpret" }, { href: "#fix", label: "Fix" }, { href: "#faq", label: "FAQ" }, { href: "#sources", label: "Sources" }]}>
    <div className="flex flex-col"><div className="container pt-6"><BreadcrumbSchema items={[{ name: "Tools", href: "/tools" }, { name: "DNS leak test", href: "/tools/dns-leak-test" }]} /></div>
      <main className="container max-w-5xl py-8 lg:py-12"><header className="mb-10 max-w-4xl"><p className="mb-3 text-sm font-semibold uppercase tracking-wide text-primary">Privacy diagnostic tool</p><h1 className="text-4xl font-bold tracking-tight md:text-5xl">{dnsLeakEditorialTitle}</h1><p className="mt-5 text-xl text-muted-foreground">{dnsLeakEditorialDescription}</p><div className="mt-5 flex items-start gap-3 rounded-xl border border-amber-500/30 bg-amber-500/10 p-4 text-sm leading-6"><AlertTriangle className="mt-0.5 size-5 shrink-0 text-amber-700" aria-hidden="true" /><p><strong>Evidence boundary:</strong> a DNS result is a route check, not a provider audit. Repeat it after network, browser or VPN changes and keep account, app-permission and WebRTC checks separate.</p></div><p className="mt-4 text-sm text-muted-foreground">Reviewed 13 August 2026 · DataForSEO US/English questions guide the coverage; they do not prove that a VPN prevents every leak.</p></header>

        <section id="test" className="scroll-mt-24"><h2 className="text-3xl font-bold">Run the DNS leak test</h2><p className="mt-3 max-w-3xl text-muted-foreground">Run it once without a VPN, again after connecting, and once more after switching between Wi-Fi and mobile data. Compare resolver names, organisations and locations rather than looking only for a green label.</p><div className="mt-6"><DnsLeakWidget /></div></section>

        <section id="interpret" className="mt-16 scroll-mt-24"><h2 className="text-3xl font-bold">How to interpret the result</h2><div className="mt-6 overflow-x-auto rounded-xl border"><table className="w-full min-w-[720px] text-left text-sm"><caption className="sr-only">DNS leak test interpretation guide</caption><thead className="bg-muted/60"><tr><th scope="col" className="p-4">Signal</th><th scope="col" className="p-4">What it can indicate</th><th scope="col" className="p-4">What it cannot prove</th></tr></thead><tbody className="divide-y"><tr><th scope="row" className="p-4 font-semibold">ISP resolver appears</th><td className="p-4">DNS queries may be leaving through the local network or a custom resolver.</td><td className="p-4">It does not by itself prove that every app is leaking or that the VPN is logging.</td></tr><tr><th scope="row" className="p-4 font-semibold">VPN/data-centre resolver appears</th><td className="p-4">The browser test is seeing a resolver associated with the tunnel.</td><td className="p-4">It does not verify IPv6, WebRTC, split tunnelling or other devices.</td></tr><tr><th scope="row" className="p-4 font-semibold">Mixed locations or providers</th><td className="p-4">Different paths, browser settings, networks or fallback resolvers may be active.</td><td className="p-4">Geo-location databases can be imprecise; repeat the test before diagnosing.</td></tr></tbody></table></div></section>

        <section id="fix" className="mt-16 scroll-mt-24"><h2 className="text-3xl font-bold">A practical fix checklist</h2><ol className="mt-5 grid gap-4 md:grid-cols-2">{["Disconnect the VPN and record the baseline resolver list.", "Reconnect and check the app's DNS protection, kill switch and split-tunnel settings.", "Remove custom OS DNS entries unless you understand how they interact with the VPN.", "Review browser Secure DNS/DoH and Android Private DNS settings separately.", "Repeat on IPv4 and IPv6-capable networks, then test after sleep, reconnect and network switching.", "If the issue persists, save the resolver output and follow the provider's current support instructions."].map((item, index) => <li key={item} className="flex gap-3 rounded-lg border p-4"><CheckCircle2 className="mt-0.5 size-5 shrink-0 text-green-600" aria-hidden="true" /><span><strong>{index + 1}.</strong> {item}</span></li>)}</ol><div className="mt-6 grid gap-5 md:grid-cols-3"><div className="rounded-xl border p-5"><Lock className="size-6 text-primary" aria-hidden="true" /><h3 className="mt-3 font-semibold">DNS path</h3><p className="mt-2 text-sm text-muted-foreground">A VPN can route DNS through its tunnel, but custom settings and browser features can change the path.</p></div><div className="rounded-xl border p-5"><ShieldCheck className="size-6 text-primary" aria-hidden="true" /><h3 className="mt-3 font-semibold">Kill switch</h3><p className="mt-2 text-sm text-muted-foreground">A kill switch may block traffic during tunnel failure; confirm what it covers on your device.</p></div><div className="rounded-xl border p-5"><CircleHelp className="size-6 text-primary" aria-hidden="true" /><h3 className="mt-3 font-semibold">Broader privacy</h3><p className="mt-2 text-sm text-muted-foreground">For a broader threat model, compare our <Link href="/best/vpn-privacy" className="text-primary underline">VPN privacy guide</Link> and <Link href="/blog/vpn-leak-testing-tools-compared-2026" className="text-primary underline">leak-testing tools guide</Link>.</p></div></div></section>

        <section className="mt-16 scroll-mt-24"><h2 className="text-3xl font-bold">VPN options to verify</h2><p className="mt-3 max-w-3xl text-muted-foreground">These are contextual starting points for readers who found a routing problem. They are not a guarantee of leak-free behaviour; open the provider documentation, test your device and check the current plan before subscribing.</p><div className="mt-6 grid gap-5 md:grid-cols-3">{providers.map((provider) => <ProviderCard key={provider.id} provider={provider} />)}</div></section>

        <section id="faq" className="mt-16 scroll-mt-24"><h2 className="text-3xl font-bold">DNS leak FAQ</h2><div className="mt-5 space-y-5">{dnsLeakEditorialFaq.map((item) => <div key={item.question} className="rounded-xl border p-5"><h3 className="font-semibold">{item.question}</h3><p className="mt-2 text-muted-foreground">{item.answer}</p></div>)}</div><FAQSchema title="DNS leak test FAQ" faqs={dnsLeakEditorialFaq} /></section>

        <section id="sources" className="mt-16 scroll-mt-24 border-t pt-8"><h2 className="text-2xl font-bold">Sources and related checks</h2><p className="mt-2 text-sm text-muted-foreground">The research dossier was refreshed 13 August 2026. Provider behaviour and browser settings should be checked at source because they change by platform and release.</p><ul className="mt-4 grid gap-2 text-sm sm:grid-cols-2"><li><a href="https://browserleaks.com/dns" target="_blank" rel="noopener noreferrer" className="text-primary underline">BrowserLeaks DNS test reference</a></li><li><a href="https://protonvpn.com/support/dns-leaks-privacy" target="_blank" rel="noopener noreferrer" className="text-primary underline">Proton VPN: DNS leak guidance</a></li><li><Link href="/blog/vpn-leak-testing-tools-compared-2026" className="text-primary underline">Compare leak-testing tools</Link></li><li><Link href="/methodology" className="text-primary underline">ZeroToVPN methodology</Link></li></ul></section>
      </main></div>
  </BestVpnEditorialTemplate>;
}
