import { ArrowRight, CheckCircle2, ExternalLink, ShieldCheck, TriangleAlert } from "lucide-react";
import { ArticleJsonLd } from "@/components/seo/json-ld";
import { BreadcrumbSchema } from "@/components/seo/breadcrumb-schema";
import { FAQSchema } from "@/components/seo/faq-schema";
import { BestVpnEditorialTemplate } from "@/components/editorial/best-vpn-editorial-template";
import { AffiliateButton } from "@/components/vpn/affiliate-button";
import { Link } from "@/i18n/navigation";
import { getVpnAffiliateUrl, type VpnLinkSlug } from "@/lib/vpn-links";

const pageUrl = "https://www.zerotovpn.com/best/free-vpn";
const faq = [
  { question: "Is there any 100% free VPN?", answer: "Yes, some providers offer a free tier without a subscription fee. “Free” still comes with trade-offs such as limited locations, data caps, fewer simultaneous features or slower access. Read the current plan and privacy terms before installing." },
  { question: "Are free VPNs safe to use?", answer: "Safety depends on the provider, app, privacy policy, permissions and update path. Treat a free download as untrusted until you can identify the operator, the business model and current independent evidence. A free price is not evidence of privacy." },
  { question: "Can I use a free VPN for streaming?", answer: "Sometimes a free tier may connect to a streaming service, but providers often limit locations or explicitly reserve guaranteed streaming support for paid plans. We do not treat one successful playback as a stable feature." },
  { question: "Which free VPN works in China?", answer: "There is no responsible universal answer. Availability changes by network, device, protocol and date, and local rules matter. Prepare before travel and use the evidence-led China and restricted-network guides rather than a permanent-work claim." },
  { question: "Do free VPNs sell your data?", answer: "Some free VPN business models have collected or monetised user data, while others are funded by paid subscribers or another model. Check the current privacy policy, independent audits and permissions instead of applying a blanket percentage to every provider." },
];

const nav = [
  { href: "#quick-answer", label: "Quick answer" },
  { href: "#free-tiers", label: "Free tiers" },
  { href: "#safety", label: "Safety" },
  { href: "#paid-upgrade", label: "When to pay" },
  { href: "#faq", label: "FAQ" },
  { href: "#sources", label: "Sources" },
] as const;

function FreeTierCard({ rank, name, vpnId, badge, description, limit, bestFor, officialUrl, officialLabel }: { rank: number; name: string; vpnId: VpnLinkSlug; badge?: string; description: string; limit: string; bestFor: string; officialUrl: string; officialLabel: string }) {
  return (
    <article className="rounded-2xl border bg-card p-5 shadow-sm">
      <div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.16em] text-primary">{rank}. {badge ?? "Free tier"}</p><h3 className="mt-2 text-xl font-bold">{name}</h3></div><ShieldCheck className="size-5 text-emerald-600" aria-hidden="true" /></div>
      <p className="mt-3 text-sm leading-6 text-muted-foreground">{description}</p>
      <dl className="mt-5 grid gap-3 text-sm"><div className="rounded-lg bg-muted/50 p-3"><dt className="font-semibold">Data / access boundary</dt><dd className="mt-1 text-muted-foreground">{limit}</dd></div><div className="rounded-lg bg-muted/50 p-3"><dt className="font-semibold">Best fit</dt><dd className="mt-1 text-muted-foreground">{bestFor}</dd></div></dl>
      <div className="mt-5 flex flex-wrap items-center gap-3"><AffiliateButton vpnId={vpnId} vpnName={name} affiliateUrl={getVpnAffiliateUrl(vpnId)} size="sm">Visit {name}</AffiliateButton><a href={officialUrl} target="_blank" rel="noopener noreferrer" className="inline-flex items-center gap-1 text-sm font-semibold underline underline-offset-4">{officialLabel}<ExternalLink className="size-3.5" aria-hidden="true" /></a></div>
    </article>
  );
}

export function FreeVpnEditorialPage() {
  return (
    <>
      <ArticleJsonLd title="Best Free VPNs: Safety, Limits and Trade-offs" description="Compare free VPN tiers by data limits, privacy evidence, locations and realistic use cases without blanket safety claims." url={pageUrl} datePublished="2026-01-01" dateModified="2026-08-11" />
      <BreadcrumbSchema items={[{ name: "Best VPNs", href: "/best/best-vpn" }, { name: "Free VPNs", href: "/best/free-vpn" }]} />
      <FAQSchema title="Free VPN FAQ" faqs={faq} />
      <BestVpnEditorialTemplate navigation={nav}>
        <article>
          <section className="border-b bg-gradient-to-br from-emerald-500/10 via-background to-background py-14 lg:py-20"><div className="container max-w-5xl"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Updated August 11, 2026 · free-tier guide</p><h1 className="mt-4 text-4xl font-bold tracking-tight sm:text-6xl">Best free VPNs: what is actually free, safe and useful?</h1><p className="mt-6 text-xl leading-8 text-muted-foreground">A free VPN can be a sensible choice for light, occasional use—but “free” does not mean unlimited, private or suitable for censorship and streaming. Compare the plan boundary, privacy evidence and failure mode before you connect.</p><p className="mt-5 text-sm leading-6 text-muted-foreground">Independent editorial research. Affiliate links may earn us a commission; <Link href="/affiliate-disclosure" className="underline">read our disclosure</Link>. Provider plans and policies can change.</p></div></div></section>

          <section id="quick-answer" className="container max-w-5xl scroll-mt-24 py-10 lg:py-14"><div className="rounded-2xl border border-emerald-300 bg-emerald-50 p-6 text-emerald-950"><h2 className="text-2xl font-bold">Quick answer</h2><p className="mt-3 max-w-3xl leading-7">For a no-cost starting point, Proton VPN Free documents unlimited bandwidth and a free plan; Windscribe documents a monthly data allowance; TunnelBear documents a smaller monthly allowance. Those facts do not make any tier the best choice for every device, country or service. Check the official plan pages linked below.</p></div></section>

          <section id="free-tiers" className="container max-w-5xl scroll-mt-24 py-10 lg:py-14"><div className="max-w-3xl"><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Free-tier shortlist</p><h2 className="mt-3 text-3xl font-bold">Compare the limit you will actually hit</h2><p className="mt-4 leading-7 text-muted-foreground">These cards separate provider-documented plan facts from our editorial fit. They are not a claim that a free tier will unblock a particular service.</p></div><div className="mt-7 grid gap-5 lg:grid-cols-3"><FreeTierCard rank={1} name="Proton VPN Free" vpnId="protonvpn" badge="Most usable data allowance" description="Proton’s official free-plan page says the tier is free forever, ad-free and has no data limit. Server selection and streaming guarantees remain more limited than on paid plans." limit="Unlimited bandwidth; limited free locations and plan features." bestFor="Occasional browsing and a no-cost privacy baseline." officialUrl="https://protonvpn.com/free-vpn/download" officialLabel="Verify free plan" /><FreeTierCard rank={2} name="Windscribe Free" vpnId="windscribe" badge="Flexible capped tier" description="Windscribe documents 10 GB per month with a confirmed email (2 GB without one), 10 free countries and unlimited devices on its current free Windows page." limit="10 GB/month with confirmed email; 2 GB without; fewer locations than Pro." bestFor="Several devices with light, capped usage." officialUrl="https://windscribe.com/features/windows" officialLabel="Verify free plan" /><FreeTierCard rank={3} name="TunnelBear Free" vpnId="tunnelbear" badge="Beginner-friendly trial tier" description="TunnelBear’s current pricing page documents 2 GB of secure browsing for its free option. That makes it a small test tier rather than a general streaming or travel plan." limit="2 GB of secure browsing; check current platform availability." bestFor="Testing the app before deciding whether to pay." officialUrl="https://www.tunnelbear.com/pricing/" officialLabel="Verify free plan" /></div></section>

          <section id="safety" className="scroll-mt-24 border-y bg-muted/30 py-12 lg:py-16"><div className="container max-w-5xl"><div className="grid gap-8 lg:grid-cols-[0.85fr_1.15fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">Safety checklist</p><h2 className="mt-3 text-3xl font-bold">A free download is not a privacy audit</h2><p className="mt-4 leading-7 text-muted-foreground">Before installing any free VPN, save the current privacy policy and app-store publisher, check permissions and confirm how the provider funds the service. Avoid sideloads, fake “100% free” browser extensions and apps that promise impossible anonymity.</p></div><ul className="grid gap-3 sm:grid-cols-2">{["Identify the operator and official download source.","Read the current privacy policy and retention language.","Check permissions, update history and independent audits.","Record data, location and device limits before connecting.","Test DNS/traffic fallback and the kill-switch behaviour.","Do not use a free tier for high-risk work without a threat model."].map((item) => <li key={item} className="flex gap-3 border bg-card p-4 text-sm leading-6"><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-emerald-600" aria-hidden="true" />{item}</li>)}</ul></div></div></section>

          <section id="paid-upgrade" className="container max-w-5xl scroll-mt-24 py-12 lg:py-16"><div className="grid gap-8 lg:grid-cols-[0.8fr_1.2fr]"><div><p className="text-sm font-semibold uppercase tracking-[0.16em] text-primary">When to pay</p><h2 className="mt-3 text-3xl font-bold">Upgrade for a requirement, not a fear headline</h2><p className="mt-4 leading-7 text-muted-foreground">A paid plan may add locations, support, higher limits, multi-device controls or streaming features. Compare the exact need and current renewal terms rather than assuming paid means private or guaranteed.</p></div><div className="rounded-xl border border-amber-300 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><div className="flex gap-3"><TriangleAlert className="mt-0.5 size-5 shrink-0" aria-hidden="true" /><p><strong>Restricted networks:</strong> a free tier is not evidence that a provider works in China, Iran or on a blocked Wi-Fi network. Use the <Link href="/guides/vpn-for-restricted-networks" className="underline">restricted-network guide</Link>, <Link href="/guides/vpn-obfuscation-explained" className="underline">obfuscation guide</Link> and relevant country dossier.</p></div><div className="mt-5"><Link href="/best/best-vpn" className="inline-flex items-center gap-2 rounded-lg border px-4 py-2 font-semibold hover:bg-muted">Compare paid plans <ArrowRight className="size-4" aria-hidden="true" /></Link></div></div></div></section>

          <section id="faq" className="container max-w-5xl scroll-mt-24 py-12 lg:py-16"><h2 className="text-3xl font-bold">Free VPN FAQ</h2><div className="mt-6 divide-y rounded-xl border">{faq.map((item) => <details key={item.question} className="group p-5"><summary className="cursor-pointer pr-8 font-semibold">{item.question}<ArrowRight className="float-right size-4 transition-transform group-open:rotate-90" aria-hidden="true" /></summary><p className="mt-3 max-w-3xl leading-7 text-muted-foreground">{item.answer}</p></details>)}</div></section>

          <section id="sources" className="container max-w-5xl scroll-mt-24 border-t py-12 lg:py-16"><h2 className="text-3xl font-bold">Sources and related guides</h2><ul className="mt-5 list-disc space-y-2 pl-5 text-sm leading-6 text-muted-foreground"><li><a className="underline" href="https://protonvpn.com/free-vpn/download" target="_blank" rel="noopener noreferrer">Proton VPN Free plan</a> — bandwidth, plan and streaming boundaries.</li><li><a className="underline" href="https://windscribe.com/features/windows" target="_blank" rel="noopener noreferrer">Windscribe Free plan</a> — data and location limits.</li><li><a className="underline" href="https://www.tunnelbear.com/pricing/" target="_blank" rel="noopener noreferrer">TunnelBear pricing</a> — current free allowance.</li><li>DataForSEO US/English dossier fetched August 11, 2026: PAA questions about truly free VPNs, safety, no-card access, streaming and China. Metrics prioritise questions; they do not prove provider outcomes.</li></ul><p className="mt-6 text-sm leading-6 text-muted-foreground">Continue with the <Link href="/guides/vpn-for-travel" className="underline">travel guide</Link>, <Link href="/guides/public-wifi-safety" className="underline">public Wi-Fi safety guide</Link>, <Link href="/guides/vpn-protocols-explained" className="underline">protocol guide</Link> or <Link href="/best/best-vpn" className="underline">Best VPN comparison</Link>.</p></section>
        </article>
      </BestVpnEditorialTemplate>
    </>
  );
}
